rust-x-bindings/rust-xcb

build.rs
=> Fix compilation of build script.

examples/ffi_screen_info.rs
Super simple. If I notice more, I'll try and include them in one big commit.
=> Fix unused warning

src/base.rs
=> Allow to create connections without xlib when the xlib_xcb feature is enabled

rs_client.py, xcbgen/state.py, xcbgen/xtypes.py
=> Incorrect return types 72

examples/randr_screen_modes.rs, scripts/test_examples.sh
=> randr_screen_modes example

build.rs
Adds conditional compilation in `build.rs` to enable cross compilation from windows.
=> Enable cross compilation from Windows

build/cg/struct.rs
=> string returned from X can be invalid utf-8

build/parse.rs
using `?` on `read_event` removes a level of pattern and also the `Err` fallback
=> simplify parse pattern matching

build/cg/switch.rs
generated code diff:
```diff
diff -ur gen/previous/xinput.rs gen/current/xinput.rs
--- gen/previous/xinput.rs	2021-11-29 13:50:35.144344037 +0100
+++ gen/current/xinput.rs	2021-11-30 22:26:09.942750265 +0100
@@ -5719,6 +5719,7 @@
max_keycode: KeyCode,
num_keys: u16,
},
+    /// The value is the number of buttons
Button(u16),
Valuator {
axes_len: u8,
@@ -5729,6 +5730,59 @@
}
impl InputInfoInfo {
+    #[allow(unused_assignments)]
+    pub(crate) unsafe fn from_wire_data_and_expr(
+        params: InputInfoInfoParams,
+        wire_data: *const u8,
+        expr: usize,
+    ) -> Self {
+        let InputInfoInfoParams { class_id } = params;
+        if expr == (InputClass::Key as usize) {
+            let mut offset = 0usize;
+            let min_keycode = *(wire_data.add(offset) as *const …
```
=> switch constructor

build/cg/switch.rs
[diff.txt](https://github.com/rust-x-bindings/rust-xcb/files/7629042/diff.txt)
=> remove fieldrefs from switches

src/base.rs
This boils down to using connection in error state.
The solution is to check for error before caching extension data.
=> fix segfault of failed connection with extension

build/cg/event.rs
=> fix type inconsistency of event ctor params

Cargo.toml, src/base.rs
remove dependency to `log`
remove build-dependency to `libc`
=> Clear dependencies

build/cg/enum.rs, build/cg/event.rs, build/cg/switch.rs, build/cg/union.rs, build/parse.rs, src/event.rs, src/lib.rs
=> Fix panic when present feature is enabled

src/base.rs
=> impl AsRef<Connection> for Connection

build/cg/enum.rs, build/cg/mod.rs, build/cg/switch.rs, build/cg/xid.rs, src/test.rs
=> Cw Ordering

src/lib.rs
I'm experimenting with creating a Window Manager with this library, but I've found if my WM starts up before any other X windows, then none of the Atoms have been interned in the X server yet, so `Atoms::intern_all` actually does nothing (all atoms are returned as `ATOM_NONE`).
I think what I want to do is make my WM intern all the Atoms that don't already exist... It seems a way to do is is to send `x::InternAtom` with `only_if_exists: false`. As far as I understand it, this is the "right" way to do this:
> if `only_if_exists`, is set to `false`, and the string does not exist on the server, then it is going to be stored, and an atom is returned for that string. if the string does exist, then the atom identifying it, is returned.
> 
> From …
=> Extend atoms_struct macro to allow configuring only_if_exists

src/base.rs
This code will panic:
```rust
use display_info::DisplayInfo;
fn main() {
let info = DisplayInfo::all().unwrap();
dbg!(info);
}
```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x7ffcdcba06d3'
=> fix align error

src/event.rs
=> impl Send and Sync for UnknownEvent

src/event.rs
=> Unknown GE_GENRIC event resolves to Event::Unknown

build/cg/request.rs, src/base.rs
=> add `Reply::as_raw`
