rust-x-bindings/rust-xcb

README.md
examples/drawing.rs

Ensure that the key press that is checked for in the
event loop is emitted.

Include KEY_PRESS in masked events in examples.

---

examples/randr_crtc_listen.rs
rs_client.py

We simply monkey-patch the type object for `StructPtr`s and handle
them in a special fashion, as well as generate basic `transmute`-based
accessors for struct members of unions, allowing for a nice solution to #27.
This builds with `--features=debug_all`, but further testing (and possibly more through inspection of the problem) is necessary, as this just cures the symptoms, but isn't really beautiful as a solution. I'd love to hear whether this is the right direction, however.

Implemented primitive union accessors for struct memebers

---

src/base.rs

The implementations aren't the smartest or most useful, but I think
they're better than no implementation. With this change, if the 'thread'
feature is enabled, the error types exposed by `xcb` can be used with
`error-chain`.

Implement Error/Display for GenericError and ConnError.

---

build.rs
rs_client.py

This patch enables vendoring of the crate.
The issue is that cargo-vendor stores checksums of all crate's source files after the first build. Unfortunately this crate generates slightly different sources every time, which makes it hard to vendor: cargo's checksum test fails on build. There is currently no way to make cargo-vendor ignore some of the source files when calculating checksums.
This small patch makes `rs_client.py` always generate identical source code for a single crate version:
1. Timestamp at the top of generated files is replaced with version tag.
2. Iteration of Python dicts and sets is made deterministic by setting PYTHONHASHSEED envvar.

Make source generation deterministic

---

src/base.rs

When using rust-xcb to access an already existing xcb connection (for example, one from glutin), a way to avoid calling the destructor was needed. This pattern is similar to IntoRawFd from the standard library.

Add Connection.into_raw_conn

---

build.rs

The build.rs file requires python3 to execute, but when it is missing it
just prints a "No such file or directory" error.
To make this dependency error more clear, an `expect` has been added
that informs the user that the build dependency python3 is missing.
This fixes #49.

Improve missing python error in build.rs

---

src/base.rs

when supplying a ```displayname``` to get  connection to xcb, ```CString``` goes out of scope when ```map_or``` returns...

xcb::Connection::connect -> Fix use after free on displayname

---

examples/randr_crtc_info.rs
rs_client.py
src/base.rs
src/ffi/base.rs

Apparently people order cookies and don't want to eat them. But```rust-xcb``` does not provide a way to call ```xcb_discard_reply``` because ```sequence``` field is not public. This PR goes all the way to clean-up cookies when they go out of scope. 
Fixes #57.

Implement Drop on Cookies

---

xcbgen/matcher.py
xcbgen/state.py

`cElementTree` has been deprecated since Python 3.3; `ElementTree` will use a fast implementation whenever available.
`cElementTree` is actually removed as of Python 3.9 beta 1, and on Python 3.8 it's an alias to `ElementTree`.
See https://docs.python.org/3.8/library/xml.etree.elementtree.html
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rtbo/rust-xcb/87)

Use `ElementTree` instead of `cElementTree`

---

build.rs

FreeBSD does not have the needed libraries
in the default search path.
This patch adds the needed folder to the
search path of `rustc` on FreeBSD.

Make the library build on FreeBSD

---

Cargo.toml

Currently, the documentation on docs.rs is generated only for the default features, meaning it barely contains any XCB modules.
docs.rs has [an option to generate documentation for all features](https://docs.rs/about). This pull request enables it.
docs.rs should pick it up with the next release of the crate, and then it won't be necessary to host the documentation separately on http://rtbo.github.io/rust-xcb/xcb/index.html

Generate documentation for all features

---

build/cg/mod.rs

Aim is more ergonomic type names for parameters of `render::CreatePicture`, `render::ChangePicture`, `sync::CreateAlarm` and `sync::ChangeAlarm`.
The diff of generated code is as follow:
```diff
diff -ur gen/previous/render.rs gen/current/render.rs
--- gen/previous/render.rs	2021-11-14 21:53:23.360727270 +0100
+++ gen/current/render.rs	2021-11-15 11:34:45.063334376 +0100
@@ -557,7 +557,7 @@
}
bitflags! {
-    pub struct Cp: u32 {
+    pub struct CpMask: u32 {
const REPEAT = 0x00000001;
const ALPHA_MAP = 0x00000002;
const ALPHA_X_ORIGIN = 0x00000004;
@@ -1499,12 +1499,12 @@
}
#[derive(Copy, Clone, Debug)]
-pub struct CreatePictureValueListParams {
+pub struct CpParams {
pub value_mask: usize,
}
#[derive(Clone, Debug)]
-pub enum CreatePictureValueList {
+pub enum Cp {
Repeat(u32), …
```

Switches rename

---

TODO_v1.md
build/cg/event.rs
build/cg/mod.rs
build/cg/request.rs
build/cg/struct.rs
build/cg/union.rs
build/parse.rs

This collaterally `impl Wired` for all events and fixes a serialization bug (wrong fixed/var sections)
The most interesting diff is `xinput`:
```diff
--- gen/previous/xinput.rs	2021-11-16 23:29:51.666673467 +0100
+++ gen/current/xinput.rs	2021-11-16 23:32:09.240007180 +0100
@@ -606,6 +606,24 @@
}
}
+impl base::Wired for DeviceValuatorEvent {
+    type Params = ();
+
+    unsafe fn compute_wire_len(_ptr: *const u8, _params: ()) -> usize {
+        32
+    }
+
+    fn wire_len(&self) -> usize {
+        32usize
+    }
+
+    fn serialize(&self, wire_buf: &mut [u8]) -> usize {
+        debug_assert!(wire_buf.len() >= self.wire_len());
+        (&mut wire_buf[0..self.wire_len()]).copy_from_slice(self.as_slice());
+        self.wire_len()
+    }
+}
+
impl Drop for DeviceValuatorEvent {
fn …
```

support for <eventstruct> and xinput::SendExtensionEvent

---

README.md
build/cg/switch.rs
examples/basic_window.rs
examples/drawing.rs
examples/opengl_window.rs
src/base.rs
src/lib.rs
src/test.rs

Fix the use of mask and enums in switch members.
The generated code diff:
```diff
diff -ur gen/previous/render.rs gen/current/render.rs
--- gen/previous/render.rs	2021-11-18 22:01:37.533323442 +0100
+++ gen/current/render.rs	2021-11-18 23:09:22.753332735 +0100
@@ -1505,7 +1505,7 @@
#[derive(Clone, Debug)]
pub enum Cp {
-    Repeat(u32),
+    Repeat(Repeat),
AlphaMap(Picture),
AlphaXOrigin(i32),
AlphaYOrigin(i32),
@@ -1513,9 +1513,9 @@
ClipYOrigin(i32),
ClipMask(xproto::Pixmap),
GraphicsExposure(u32),
-    SubwindowMode(u32),
-    PolyEdge(u32),
-    PolyMode(u32),
+    SubwindowMode(xproto::SubwindowMode),
+    PolyEdge(PolyEdge),
+    PolyMode(PolyMode),
Dither(xproto::Atom),
ComponentAlpha(u32),
}
@@ -1716,7 +1716,8 @@
for el in self.iter() {
match el {
Cp::Repeat(repeat) => {
- …
```

Fix switch mask

---

build/cg/mod.rs

`String8` was defined as `char`, but should be `u8`.
It misses probably opportunities to be treated as `&str`, but at least is correct regarding the protocol.
diff:
```diff
diff -ur gen/previous/xkb.rs gen/current/xkb.rs
--- gen/previous/xkb.rs	2021-11-21 11:45:35.676221006 +0100
+++ gen/current/xkb.rs	2021-11-21 21:53:20.273232063 +0100
@@ -5010,7 +5010,7 @@
}
}
-pub type String8 = char;
+pub type String8 = u8;
pub struct Outline {
data: [u8],
@@ -5359,57 +5359,13 @@
}
}
-#[derive(Copy, Clone)]
+#[derive(Copy, Clone, Debug)]
+#[repr(C)]
pub struct Key {
-    data: [u8; 8],
-}
-
-#[allow(unused_parens)]
-impl Key {
-    pub(crate) unsafe fn from_data<D: AsRef<[u8]> + ?Sized>(data: &D) -> &Key {
-        debug_assert_eq!(data.as_ref().len(), 8);
-        &*(data.as_ref() as *const [u8] as …
```

fix xkb::String8

---

build/cg/request.rs
build/cg/struct.rs
src/lib.rs

extract of diff:
```diff
diff -ur gen/previous/dri2.rs gen/current/dri2.rs
--- gen/previous/dri2.rs	2021-11-21 22:18:25.789998318 +0100
+++ gen/current/dri2.rs	2021-11-21 22:51:13.183312952 +0100
@@ -421,6 +421,24 @@
&*(data.as_ref() as *const [u8] as *const Dri2Buffer)
}
+    /// Construct a new [Dri2Buffer].
+    #[allow(unused_assignments, unused_unsafe)]
+    pub fn new(attachment: Attachment, name: u32, pitch: u32, cpp: u32, flags: u32) -> Dri2Buffer {
+        unsafe {
+            let mut wire_buf = [0u8; 20];
+            let mut wire_off = 0usize;
+
+            wire_off +=
+                std::mem::transmute::<_, u32>(attachment).serialize(&mut wire_buf[wire_off..]);
+            wire_off += name.serialize(&mut wire_buf[wire_off..]);
+            wire_off += …
```

emit struct ctor

---

build/cg/struct.rs

diff:
```diff
diff -ur gen/previous/xinput.rs gen/current/xinput.rs
--- gen/previous/xinput.rs	2021-12-04 12:12:32.326912508 +0100
+++ gen/current/xinput.rs	2021-12-05 09:53:16.828439873 +0100
@@ -5928,8 +5928,9 @@
}
pub fn info(&self) -> InputInfoInfo {
+        let class_id = self.class_id();
let params = InputInfoInfoParams {
-            class_id: self.class_id() as usize,
+            class_id: class_id as usize,
};
let offset = 2usize;
let switch = (self.class_id() as usize);
@@ -6026,6 +6027,7 @@
f.debug_struct("InputInfo")
.field("class_id", &self.class_id())
.field("len", &self.len())
+            .field("info", &self.info())
.finish()
}
}
@@ -6035,6 +6037,7 @@
f.debug_struct("InputInfoBuf")
.field("class_id", &self.class_id())
.field("len", &self.len())
+ …
```

Switch acc debug

---

build/cg/struct.rs

diff:
```diff
diff -ur gen/previous/randr.rs gen/current/randr.rs
--- gen/previous/randr.rs	2021-12-05 10:01:04.962013862 +0100
+++ gen/current/randr.rs	2021-12-05 10:23:15.074831143 +0100
@@ -4977,6 +4977,12 @@
impl std::fmt::Debug for GetOutputPropertyReply {
fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        let data: Box<dyn std::fmt::Debug> = match self.format() {
+            8 => Box::new(self.data::<u8>()),
+            16 => Box::new(self.data::<u16>()),
+            32 => Box::new(self.data::<u32>()),
+            format => unreachable!("impossible prop format: {}", format),
+        };
f.debug_struct("GetOutputPropertyReply")
.field("response_type", &self.response_type())
.field("format", &self.format())
@@ -4986,7 +4992,7 @@
.field("bytes_after", …
```

match format in property debug impl

---

build/cg/error.rs
build/cg/event.rs

Rationale: they own their data and do not mutate any state.
`Send` and `Sync` is therefore safe to implement.
fixes #128

events and errors impl Send and Sync

---

TODO_v1.md
build/cg/switch.rs

code generation diff: 
```diff
diff -ur gen/previous/xinput.rs gen/current/xinput.rs
--- gen/previous/xinput.rs	2021-12-19 22:13:53.320098351 +0100
+++ gen/current/xinput.rs	2021-12-19 22:30:31.316809011 +0100
@@ -11183,9 +11183,7 @@
status: u8,
iscore: u8,
},
-    Enable {
-        enable: u8,
-    },
+    Enable(u8),
AbsArea {
offset_x: u32,
offset_y: u32,
@@ -11278,7 +11276,7 @@
let enable = *(wire_data.add(offset) as *const u8);
offset += std::mem::size_of::<u8>();
offset += 3; // pad
-            return DeviceStateData::Enable { enable };
+            return DeviceStateData::Enable(enable);
}
if expr == (DeviceControl::AbsArea as usize) {
let mut offset = 0usize;
@@ -11430,7 +11428,7 @@
sz += 1;
sz += 2;
}
-            DeviceStateData::Enable { .. } => {
+ …
```

Fix enums with single field

---

build/cg/request.rs
build/cg/struct.rs

diff of code generation:
```diff
diff -ur gen/previous/dri3.rs gen/current/dri3.rs
--- gen/previous/dri3.rs	2021-12-20 11:43:47.581608182 +0100
+++ gen/current/dri3.rs	2021-12-20 12:12:31.988222480 +0100
@@ -315,9 +315,11 @@
pub fn device_fd(&self) -> RawFd {
unsafe {
-            let offset = 8usize;
-            let ptr = self.wire_ptr().add(offset) as *const RawFd;
-            *ptr
+            assert!(
+                self.nfd() == 1,
+                "Expected a single Fd for OpenReply::device_fd"
+            );
+            *(self.wire_ptr().add((32 + 4 * self.length()) as _) as *const RawFd)
}
}
}
@@ -437,9 +439,9 @@
sections[3].iov_len = base::align_pad(sections[2].iov_len, 4);
let flags = if checked {
-                base::RequestFlags::CHECKED
+ …
```

fix requests and replies with fd

---

TODO_v1.md
build/cg/error.rs
build/cg/event.rs
build/cg/request.rs
build/cg/struct.rs

In replies and in XGE events, the length field is in 4 bytes units, and starts after the 32 bytes main body.

Fix wire len calculation

---

build/cg/mod.rs
build/cg/request.rs
build/cg/struct.rs
build/cg/switch.rs
examples/basic_window.rs
examples/opengl_window.rs
examples/xinput_stylus_events.rs
src/base.rs
src/lat1_str.rs
src/lib.rs
xml/xproto.xml

rationale: X protocol specifies that strings are latin1 encoded

Do not perform UTF-8 conversions

---

build/cg/event.rs
src/base.rs
src/event.rs

This changes the `ResolveWireEvent::resolve_wire_event` to return an Option. If we assume the X server is not misbihaving it's only possible for the base xproto to get an unparseable event (if the extension the event is from is not currently enabled) so I left the unreachable! in the other ones (and used unwrap on the options in `src/event.rs:resolve_event`).
Closes #141

Don't panic for unknown events in xproto

---

src/base.rs
src/error.rs

Hi, this is a very basic implementation, it just reuses the Debug print of ProtocolError as the Display print, I don't know if xcb has some mechanism to turn the error codes into human readable messages but considering that Display doesn't have any stability guarantees and the ergonomic improvements of working with errors implementing std::error::Error I think this is better than nothing.

Implement std::error::Error for xcb::ProtocolError and xcb::Error

---

build/cg/mod.rs
build/cg/request.rs
build/ir.rs

fixes #144
generated code diff:
```diff
diff -ur gen/previous/randr.rs gen/current/randr.rs
--- gen/previous/randr.rs	2022-01-18 21:48:06.491217177 +0100
+++ gen/current/randr.rs	2022-01-18 21:51:43.624233374 +0100
@@ -4919,7 +4919,7 @@
sections[3].iov_len = base::align_pad(sections[2].iov_len, 4);
sections[4].iov_base = self.data.as_ptr() as *mut _;
-            sections[4].iov_len = self.data.len() * std::mem::size_of::<u8>();
+            sections[4].iov_len = self.data.len() * std::mem::size_of::<P>();
sections[5].iov_len = base::align_pad(sections[4].iov_len, 4);
let flags = if checked {
@@ -9489,7 +9489,7 @@
sections[3].iov_len = base::align_pad(sections[2].iov_len, 4);
sections[4].iov_base = self.data.as_ptr() as *mut _;
-            sections[4].iov_len = self.data.len() * …
```

fixing iov_len to correct value for properties

---

build/cg/error.rs
build/cg/event.rs
build/cg/mod.rs
build/cg/request.rs
build/cg/struct.rs
build/cg/switch.rs
build/cg/union.rs
examples/opengl_window.rs
src/base.rs
src/event.rs
src/test.rs

Refactor traits

---

build/cg/mod.rs
build/cg/xid.rs
src/test.rs

Allows to use `Atom` or `Window` as `HashMap` keys.

Xid types impl Hash

---

build/cg/mod.rs

instead of `std::os::unix::prelude::RawFd`

use `std::os::unix::io::RawFd`

---

build/cg/request.rs
examples/basic_window.rs
src/lib.rs
xml/xproto.xml

code is better than speech:
```rust
xcb::atoms_struct!(
struct Atoms {
wm_protocols    => b"WM_PROTOCOLS",
wm_del_window   => b"WM_DELETE_WINDOW",
}
);
fn main() -> xcb::Result<()> {
// ...
let atoms = Atoms::intern_all(&conn)?;
conn.check_request(conn.send_request_checked(&x::ChangeProperty {
mode: x::PropMode::Replace,
window,
property: atoms.wm_protocols,
r#type: x::ATOM_ATOM,
data: &[atoms.wm_del_window],
}))?;
// ...
}
```

`atoms_struct!` macro

---

examples/basic_window.rs
src/lib.rs

code is better than speech:
```rust
xcb::atoms_struct!(
#[derive(Debug, Copy, Clone)]
struct Atoms {
wm_protocols    => b"WM_PROTOCOLS",
wm_del_window   => b"WM_DELETE_WINDOW",
}
);
fn main() -> xcb::Result<()> {
// ...
let atoms = Atoms::intern_all(&conn)?;
conn.check_request(conn.send_request_checked(&x::ChangeProperty {
mode: x::PropMode::Replace,
window,
property: atoms.wm_protocols,
r#type: x::ATOM_ATOM,
data: &[atoms.wm_del_window],
}))?;
// ...
}
```

add possible attributes in atoms_struct!

---

src/lib.rs

The main usecase this enables is putting doc comments on the fields as
they get desugared to `#[doc="..."]`-style attributes
---
I had a struct in my app that could use this macro but needed this feature, so I decided to add it myself

Allow attributes on fields inside `atoms_struct!`

---

Cargo.toml
examples/screenshot.rs

Example utility that takes a screenshot with `xcb_get_image` and writes it to disk as a png.

Add a screenshot example utility

---

build/cg/struct.rs

Fixes #186
---
This is behaviourally the same as the patch I showed, but with a better (IMO) note about why we do what we do here

Mark fields named `width` or `height` public even if they're fieldref

---

build/cg/event.rs
src/base.rs
src/event.rs

In some ffi scenarios it is necessary to extract the underlying
event pointer.  The `Event::as_raw` method serves this purpose.
I couldn't implement the `Raw<>` trait for `Event` because the
`from_raw` method requires additional context in order to perform
the inverse of the `as_raw` method, so `Event::as_raw` is just
a standalone method.
I added `Connection::resolve_event` as the inverse operation
to give some symmetry.
closes: https://github.com/rust-x-bindings/rust-xcb/issues/188

Add Event::as_raw(), Connection::resolve_event()

---

src/base.rs

Avoid this segfault:
```
>>> bt
#0  XGetXCBConnection (dpy=0x0) at /usr/src/debug/libX11-1.7.3.1-2.fc36.x86_64/src/x11_xcb.c:9
#1  0x0000555556eee5c7 in xcb::base::Connection::connect_with_xlib_display_and_extensions (mandatory=..., optional=...) at /home/wez/.cargo/git/checkouts/rust-xcb-4cfa40fd56e21cc5/362404a/src/base.rs:756
#2  0x0000555556bee1ae in window::os::x11::connection::XConnection::create_new () at window/src/os/x11/connection.rs:324
#3  0x0000555556ba7480 in window::os::x_and_wayland::Connection::create_new () at window/src/os/x_and_wayland.rs:49
#4  0x0000555555a437e2 in window::connection::ConnectionOps::init<window::os::x_and_wayland::Connection> () at /home/wez/wez-personal/wezterm/window/src/connection.rs:30
#5  0x0000555555a6264c in …
```

avoid segfault if eg: DISPLAY is unset when using xlib

---

build/cg/struct.rs
gen/diff.sh

There's a preexisting whitelist of properties/fields that should not be
hidden just because they appear as a part of another expression (most
notably, lists) as a `<fieldref>` expression.
For the client code it's important to check the format, otherwise the
code might panic due to the assert inside `.data::<PropEl>()` accessor.
Fixes #209

Expose "format" property getter

---

.github/workflows/lint.yml
Cargo.toml
src/base.rs

There is a new crate as-raw-xcb-connection providing a trait for getting a raw pointer for a libxcb xcb_connection_t. Implement this trait for Connection.
Closes: https://github.com/rust-x-bindings/rust-xcb/issues/217
Signed-off-by: Uli Schlachter <psychon@znc.in>
---
This is a draft since I want to wait for version 1.0 of AsRawXcbConnection before merging. See https://github.com/psychon/as-raw-xcb-connection/issues/1

Implement AsRawXcbConnection for Connection

---

examples/xkb_init.rs

The existing assert phrasing gives the impression that this library does not support xkb-1.0, while the code around it actually verifies that this version is in use. This PR adjusts the phrasing of the message to make the meaning somewhat more easy to understand.

Clarify phrasing of xkb example error message

---

Cargo.toml
build/parse.rs

Update quick-xml, as it will soon not be supported anymore by future versions of Rust

---

src/lib.rs

This pull request fix a simple missing "question mark operator" on lib.rs docs.

Missing question mark operator on docs

---

CHANGELOG.md
Cargo.toml

Hi @rtbo would you please be so kind and create a new release for the quick-xml fix?
I was not sure weather this is a 1.2.1 or 1.3.0 release because the `Error` enum in the build folder changes its public interface, but i though as this is only used for building and not an exported Error of this crate, it probably still fits in 1.2.1.
In case you have further requests or questions, or want me to change it to 1.3.0, just answer me :)

prepare 1.2.1 release

---

build/cg/struct.rs

When creating a new PictformInfo() I received the following error:
`thread 'test::test_pictforminfo' panicked at 'source slice length (16) does not match destination slice length (20)', /home/oliver/Dokumente/dev/reMenu/target/debug/build/xcb-22e5b0ca74ae1e36/out/render.rs:639:18`
This snippet can trigger the error:
```rust
let pfi = render::Pictforminfo::new(
render::Pictformat::none(),
render::PictType::Direct,
32,
render::Directformat {
red_shift: 16,
red_mask: 0xFF,
green_shift: 8,
green_mask: 0xFF,
blue_shift: 0,
blue_mask: 0xFF,
alpha_shift: 24,
alpha_mask: 0xFF,
},
x::Colormap::none(),
);
```
After some testing, I found that WireOut::serialize does not truncate data passed to it but consumes the whole chunk. From the documentation and its use in the code base, I concluded that this …

Add truncation to WireOut::serialize

---

build/cg/enum.rs

Use the implementation from https://github.com/rust-x-bindings/rust-xcb/pull/225 for this, rather than reimplementing the serialization logic inline.
refs: https://github.com/rust-x-bindings/rust-xcb/issues/229
refs: https://github.com/wez/wezterm/issues/3838

fix alignment for SendEventDest

---

CHANGELOG.md
src/lib.rs

I chose to make the names "rustier" rather than keep the C names (though those exist as doc aliases), hope that's ok

randr: Export well-known output property names

---

build/cg/struct.rs
src/base.rs

this is what is done internally as well by `copy_from_slice`, so it should deal correctly with alignment
fixes #246

dereferencing through `copy_nonoverlapping`

---

src/base.rs
src/ffi/ext.rs

Add `poll_for_reply` and `poll_for_reply_unchecked` functions

---

Cargo.toml
src/base.rs
src/lib.rs

Version 1.14 of libxcb introduced the functions xcb_total_read() and xcb_total_written(). This PR adds a feature (enabled by default) to activate these functions. Disabling the feature allows xcb-rs to support libxcb API versions before 1.14.

Add support for libxcb API before version 1.14

---

Cargo.toml
examples/present_special_event.rs
src/base.rs
src/ffi/base.rs

fixes #252 
closes #253
closes #255 
fixes #256

Fix special event API

---

Cargo.toml
examples/xkb_keyboard_mouse_event.rs
src/base.rs

add API BaseEvent::is_from_send_event

---

build/cg/error.rs
build/cg/event.rs
src/base.rs
src/error.rs
src/event.rs
src/ext.rs

- `UnknownError` introduced and returned if resolution fails instead of panicking
- Better consistency between error and event API
- `Connection::resolve_error` is introduced
- `cache_extensions_data` is public
See https://github.com/rust-x-bindings/rust-xcb/issues/265

make `resolve_error` public API

---

build/cg/struct.rs

The [`GetModifierMapping`](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:GetModifierMapping) request returns a list of keycodes. Client code needs to iterate this list in chunks of keycodes_per_modifier to visit all keycodes for each of the 8 modifiers (Shift, Lock, Control, Mod1, Mod2, Mod3, Mod4, Mod5).
The preexisting whitelist of properties/fields that should not be hidden has been extended to include this field.
Fixes #271
The generated code diff looks like this:
```diff
diff main/xinput.rs fix/xinput.rs
21933c21933
<     fn keycodes_per_modifier(&self) -> u8 {
---
>     pub fn keycodes_per_modifier(&self) -> u8 {
diff main/xproto.rs fix/xproto.rs
26678c26678
<     fn keycodes_per_modifier(&self) -> u8 {
---
>     pub fn keycodes_per_modifier(&self) -> u8 { …
```

Expose "keycodes_per_modifier" property getter

---

CHANGELOG.md
src/lib.rs

This was first done in #240, but a missing `pub` made it inaccessible.
The changelog for the original change was (accidentally) removed in #249 before appearing in a release, so we can now announce it with full parade :confetti_ball:

Export well-known RandR property names (for real)

---

build/cg/struct.rs
src/base.rs

[copy_nonoverlapping](https://doc.rust-lang.org/std/ptr/fn.copy_nonoverlapping.html) documents that its pointer must be aligned for a valid read, otherwise the call will be UB.
This patch will fix that, and I *believe* it will fix #269. (I tried @igor-petruk's oatbar at commit https://github.com/igor-petruk/oatbar/commit/baf16278217012d9bec6c54e201d47379a263458 which is what he linked in the issue, changed the Cargo.toml to depend on my local copy that had this change and did `cargo run`, and I didn't get a crash.)
This was only somewhat recently noticed because Rust started checking these preconditions in [Rust 1.78](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#asserting-unsafe-preconditions).
As some notes:
* should we add ` debug_assert!(!ptr.is_null())` to this function?
* …

Fix improper unaligned reads in `value_from_ptr`

---

src/base.rs

A double drop of FD is possible in safe code because xcb takes ownership of the FD, and `xcb::Connection::connect_to_fd` doesn't enforce that. 
This fix changes the `connect_to_fd` argument from `RawFd` to `OwnedFd` to enforce the user to release ownership of the FD.
To prevent semver clash,  current functions are going to deprecation and  new ones are created.
fix #167 
fix #282

fix unsound API `xcb::Connection::connect_to_fd*`
